### Imports

In [4]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score

### Importing the csv file

In [5]:
sonar1 = pd.read_csv("Copy of sonar data.csv",header=None)

In [6]:
sonar = sonar1[:]
sonar.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [7]:
#checking the number of rows and columns
sonar.shape

(208, 61)

In [8]:
#checking for null values
sonar.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [9]:
sonar.describe()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [10]:
sonar[60].value_counts()

60
M    111
R     97
Name: count, dtype: int64

In [11]:
Y= sonar[60]
X= sonar.drop(columns=60,axis=1)

In [12]:
X.head()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0232,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0125,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0033,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0241,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0156,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094

In [13]:
print(Y[:10])

0    R
1    R
2    R
3    R
4    R
5    R
6    R
7    R
8    R
9    R
Name: 60, dtype: object

In [14]:
x_train,x_test,y_train,y_test = train_test_split(X,Y,stratify=Y,random_state=10)

In [15]:
print(x_train.head(),y_train.head())

         0       1       2       3       4       5       6       7       8   \
111  0.0530  0.0885  0.1997  0.2604  0.3225  0.2247  0.0617  0.2287  0.0950
60   0.0130  0.0006  0.0088  0.0456  0.0525  0.0778  0.0931  0.0941  0.1711
150  0.0209  0.0278  0.0115  0.0445  0.0427  0.0766  0.1458  0.1430  0.1894
147  0.0654  0.0649  0.0737  0.1132  0.2482  0.1257  0.1797  0.0989  0.2460
57   0.0216  0.0124  0.0174  0.0152  0.0608  0.1026  0.1139  0.0877  0.1160

         9   ...      50      51      52      53      54      55      56  \
111  0.0740  ...  0.0299  0.0244  0.0199  0.0257  0.0082  0.0151  0.0171
60   0.1483  ...  0.0092  0.0078  0.0041  0.0013  0.0011  0.0045  0.0039
150  0.1853  ...  0.0133  0.0096  0.0014  0.0049  0.0039  0.0029  0.0078
147  0.3422  ...  0.0243  0.0210  0.0361  0.0239  0.0447  0.0394  0.0355
57   0.0866  ...  0.0018  0.0052  0.0049  0.0096  0.0134  0.0122  0.0047

         57      58      59
111  0.0146  0.0134  0.0056
60   0.0022  0.0023  0.0016
150  0.0047  0.0021  0.0011
147  0.0440  0.0243  0.0098
57   0.0018  0.0006  0.0023

[5 rows x 60 columns] 111    M
60     R
150    M
147    M
57     R
Name: 60, dtype: object

In [16]:
print(x_test.head(),y_test.head())

         0       1       2       3       4       5       6       7       8   \
21   0.0664  0.0575  0.0842  0.0372  0.0458  0.0771  0.0771  0.1130  0.2353
122  0.0249  0.0119  0.0277  0.0760  0.1218  0.1538  0.1192  0.1229  0.2119
108  0.0599  0.0474  0.0498  0.0387  0.1026  0.0773  0.0853  0.0447  0.1094
79   0.0108  0.0086  0.0058  0.0460  0.0752  0.0887  0.1015  0.0494  0.0472
137  0.0430  0.0902  0.0833  0.0813  0.0165  0.0277  0.0569  0.2057  0.3887

         9   ...      50      51      52      53      54      55      56  \
21   0.1838  ...  0.0135  0.0141  0.0190  0.0043  0.0036  0.0026  0.0024
122  0.2531  ...  0.0140  0.0027  0.0068  0.0150  0.0012  0.0133  0.0048
108  0.0351  ...  0.0028  0.0013  0.0005  0.0227  0.0209  0.0081  0.0117
79   0.0393  ...  0.0161  0.0029  0.0078  0.0114  0.0083  0.0058  0.0003
137  0.7106  ...  0.0208  0.0176  0.0197  0.0210  0.0141  0.0049  0.0027

         57      58      59
21   0.0162  0.0109  0.0079
122  0.0244  0.0077  0.0074
108  0.0114  0.0112  0.0100
79   0.0023  0.0026  0.0027
137  0.0162  0.0059  0.0021

[5 rows x 60 columns] 21     R
122    M
108    M
79     R
137    M
Name: 60, dtype: object

In [17]:
model= LogisticRegression()

In [18]:
model.fit(x_train,y_train)

LogisticRegression()

In [19]:
x_predictions_train = model.predict(x_train)
print(x_predictions_train,y_train)

['M' 'R' 'R' 'M' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'R' 'R' 'M' 'M'
 'R' 'M' 'R' 'R' 'M' 'M' 'M' 'R' 'R' 'M' 'M' 'M' 'M' 'R' 'M' 'M' 'R' 'R'
 'M' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'M' 'R' 'R' 'R' 'M' 'R' 'R' 'M'
 'M' 'M' 'R' 'M' 'M' 'R' 'R' 'M' 'M' 'R' 'M' 'M' 'R' 'R' 'R' 'M' 'R' 'R'
 'M' 'M' 'M' 'R' 'R' 'M' 'R' 'M' 'R' 'M' 'R' 'R' 'M' 'M' 'M' 'R' 'M' 'M'
 'M' 'R' 'M' 'M' 'M' 'R' 'R' 'M' 'R' 'R' 'M' 'M' 'M' 'M' 'R' 'R' 'R' 'M'
 'M' 'M' 'M' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'R' 'M' 'R'
 'M' 'M' 'R' 'R' 'M' 'M' 'R' 'M' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'R' 'M' 'R' 'M' 'R' 'M' 'M' 'R' 'M' 'R' 'R' 'M'] 111    M
60     R
150    M
147    M
57     R
      ..
63     R
188    M
52     R
4      R
176    M
Name: 60, Length: 156, dtype: object

In [20]:
print("Accuracy on training data is:", accuracy_score(x_predictions_train,y_train))

Accuracy on training data is: 0.8141025641025641

In [21]:
x_prediction_test= model.predict(x_test)
print(x_prediction_test[:10],y_test[:10])

['R' 'M' 'R' 'R' 'M' 'R' 'R' 'R' 'R' 'R'] 21     R
122    M
108    M
79     R
137    M
96     R
90     R
27     R
11     R
64     R
Name: 60, dtype: object

In [22]:
print("Accuracy with test data :", accuracy_score(x_prediction_test,y_test))

Accuracy with test data : 0.7692307692307693